# Generated by Django 6.0.5 on 2026-06-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineArm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Machine Arm",
                "verbose_name_plural": "Machine Arms",
                "db_table": "db_machine_arm",
            },
        ),
        migrations.CreateModel(
            name="MachineCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Machine Car",
                "verbose_name_plural": "Machine Cars",
                "db_table": "db_machine_car",
            },
        ),
        migrations.CreateModel(
            name="MachineLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Machine Language",
                "verbose_name_plural": "Machine Languages",
                "db_table": "db_machine_language",
            },
        ),
        migrations.CreateModel(
            name="MachineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Machine Model",
                "verbose_name_plural": "Machine Models",
                "db_table": "db_machine_model",
            },
        ),
        migrations.CreateModel(
            name="MachineOptional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Machine Optional",
                "verbose_name_plural": "Machine Optionals",
                "db_table": "db_machine_optional",
            },
        ),
        migrations.CreateModel(
            name="MachineSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Machine Size",
                "verbose_name_plural": "Machine Sizes",
                "db_table": "db_machine_size",
            },
        ),
        migrations.CreateModel(
            name="MachineVoltage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Machine Voltage",
                "verbose_name_plural": "Machine Voltages",
                "db_table": "db_machine_voltage",
            },
        ),
        migrations.CreateModel(
            name="MachineModelSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sap_code", models.CharField(max_length=50, unique=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sizes",
                        to="machines.machinemodel",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_sizes",
                        to="machines.machinesize",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Model Size",
                "verbose_name_plural": "Machine Model Sizes",
                "db_table": "db_machine_model_size",
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "manufacturing_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("sap_order", models.CharField(blank=True, max_length=50, null=True)),
                ("order_date", models.DateField(blank=True, null=True)),
                (
                    "transporter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "freight_insurance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="enterprises.enterprise",
                    ),
                ),
                (
                    "arm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="machines.machinearm",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="machines.machinecar",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="machines.machinelanguage",
                    ),
                ),
                (
                    "model_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="machines.machinemodelsize",
                    ),
                ),
                (
                    "optionals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="machines",
                        to="machines.machineoptional",
                    ),
                ),
                (
                    "voltage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="machines.machinevoltage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
                "db_table": "db_machine",
            },
        ),
        migrations.AddConstraint(
            model_name="machinemodelsize",
            constraint=models.UniqueConstraint(
                fields=("model", "size"), name="unique_model_size"
            ),
        ),
    ]
