"""
Command to seed all countries.

Usage: python manage.py country
"""

from django.core.management.base import BaseCommand
from core.models import Country


COUNTRIES = [
    ("Africa do Sul", "ZAF"),
    ("Afeganistao", "AFG"),
    ("Albania", "ALB"),
    ("Alemanha", "DEU"),
    ("Andorra", "AND"),
    ("Angola", "AGO"),
    ("Antigua e Barbuda", "ATG"),
    ("Arabia Saudita", "SAU"),
    ("Argelia", "DZA"),
    ("Argentina", "ARG"),
    ("Armenia", "ARM"),
    ("Australia", "AUS"),
    ("Austria", "AUT"),
    ("Azerbaijao", "AZE"),
    ("Bahamas", "BHS"),
    ("Bahrein", "BHR"),
    ("Bangladesh", "BGD"),
    ("Barbados", "BRB"),
    ("Belarus", "BLR"),
    ("Belgica", "BEL"),
    ("Belize", "BLZ"),
    ("Benin", "BEN"),
    ("Bermudas", "BMU"),
    ("Bolivia", "BOL"),
    ("Bosnia e Herzegovina", "BIH"),
    ("Botsuana", "BWA"),
    ("Brasil", "BRA"),
    ("Brunei", "BRN"),
    ("Bulgaria", "BGR"),
    ("Burkina Faso", "BFA"),
    ("Burundi", "BDI"),
    ("Butao", "BTN"),
    ("Cabo Verde", "CPV"),
    ("Camaroes", "CMR"),
    ("Camboja", "KHM"),
    ("Canada", "CAN"),
    ("Catar", "QAT"),
    ("Cazaquistao", "KAZ"),
    ("Chade", "TCD"),
    ("Chile", "CHL"),
    ("China", "CHN"),
    ("Chipre", "CYP"),
    ("Colombia", "COL"),
    ("Comores", "COM"),
    ("Congo", "COG"),
    ("Congo (RD)", "COD"),
    ("Coreia do Norte", "PRK"),
    ("Coreia do Sul", "KOR"),
    ("Costa do Marfim", "CIV"),
    ("Costa Rica", "CRI"),
    ("Croacia", "HRV"),
    ("Cuba", "CUB"),
    ("Dinamarca", "DNK"),
    ("Djibuti", "DJI"),
    ("Dominica", "DMA"),
    ("Egito", "EGY"),
    ("El Salvador", "SLV"),
    ("Emirados Arabes Unidos", "ARE"),
    ("Equador", "ECU"),
    ("Eritreia", "ERI"),
    ("Eslovaquia", "SVK"),
    ("Eslovenia", "SVN"),
    ("Espanha", "ESP"),
    ("Estados Unidos", "USA"),
    ("Estonia", "EST"),
    ("Esuatini", "SWZ"),
    ("Etiopia", "ETH"),
    ("Fiji", "FJI"),
    ("Filipinas", "PHL"),
    ("Finlandia", "FIN"),
    ("Franca", "FRA"),
    ("Gabao", "GAB"),
    ("Gambia", "GMB"),
    ("Gana", "GHA"),
    ("Georgia", "GEO"),
    ("Granada", "GRD"),
    ("Grecia", "GRC"),
    ("Guatemala", "GTM"),
    ("Guiana", "GUY"),
    ("Guine", "GIN"),
    ("Guine Equatorial", "GNQ"),
    ("Guine-Bissau", "GNB"),
    ("Haiti", "HTI"),
    ("Holanda", "NLD"),
    ("Honduras", "HND"),
    ("Hungria", "HUN"),
    ("Iemen", "YEM"),
    ("Ilhas Marshall", "MHL"),
    ("Ilhas Salomao", "SLB"),
    ("India", "IND"),
    ("Indonesia", "IDN"),
    ("Ira", "IRN"),
    ("Iraque", "IRQ"),
    ("Irlanda", "IRL"),
    ("Islandia", "ISL"),
    ("Israel", "ISR"),
    ("Italia", "ITA"),
    ("Jamaica", "JAM"),
    ("Japao", "JPN"),
    ("Jordania", "JOR"),
    ("Kiribati", "KIR"),
    ("Kosovo", "XKX"),
    ("Kuwait", "KWT"),
    ("Laos", "LAO"),
    ("Lesoto", "LSO"),
    ("Letonia", "LVA"),
    ("Libano", "LBN"),
    ("Liberia", "LBR"),
    ("Libia", "LBY"),
    ("Liechtenstein", "LIE"),
    ("Lituania", "LTU"),
    ("Luxemburgo", "LUX"),
    ("Macedonia do Norte", "MKD"),
    ("Madagascar", "MDG"),
    ("Malasia", "MYS"),
    ("Malavi", "MWI"),
    ("Maldivas", "MDV"),
    ("Mali", "MLI"),
    ("Malta", "MLT"),
    ("Marrocos", "MAR"),
    ("Mauricio", "MUS"),
    ("Mauritania", "MRT"),
    ("Mexico", "MEX"),
    ("Mianmar", "MMR"),
    ("Micronesia", "FSM"),
    ("Mocambique", "MOZ"),
    ("Moldavia", "MDA"),
    ("Monaco", "MCO"),
    ("Mongolia", "MNG"),
    ("Montenegro", "MNE"),
    ("Namibia", "NAM"),
    ("Nauru", "NRU"),
    ("Nepal", "NPL"),
    ("Nicaragua", "NIC"),
    ("Niger", "NER"),
    ("Nigeria", "NGA"),
    ("Noruega", "NOR"),
    ("Nova Caledonia", "NCL"),
    ("Nova Zelandia", "NZL"),
    ("Oma", "OMN"),
    ("Palau", "PLW"),
    ("Palestina", "PSE"),
    ("Panama", "PAN"),
    ("Papua Nova Guine", "PNG"),
    ("Paquistao", "PAK"),
    ("Paraguai", "PRY"),
    ("Peru", "PER"),
    ("Polonia", "POL"),
    ("Portugal", "PRT"),
    ("Quenia", "KEN"),
    ("Quirguistao", "KGZ"),
    ("Reino Unido", "GBR"),
    ("Republica Centro-Africana", "CAF"),
    ("Republica Dominicana", "DOM"),
    ("Republica Tcheca", "CZE"),
    ("Romenia", "ROU"),
    ("Ruanda", "RWA"),
    ("Russia", "RUS"),
    ("Samoa", "WSM"),
    ("San Marino", "SMR"),
    ("Santa Lucia", "LCA"),
    ("Sao Cristovao e Nevis", "KNA"),
    ("Sao Tome e Principe", "STP"),
    ("Sao Vicente e Granadinas", "VCT"),
    ("Seicheles", "SYC"),
    ("Senegal", "SEN"),
    ("Serra Leoa", "SLE"),
    ("Servia", "SRB"),
    ("Singapura", "SGP"),
    ("Siria", "SYR"),
    ("Somalia", "SOM"),
    ("Sri Lanka", "LKA"),
    ("Sudao", "SDN"),
    ("Sudao do Sul", "SSD"),
    ("Suecia", "SWE"),
    ("Suica", "CHE"),
    ("Suriname", "SUR"),
    ("Tailandia", "THA"),
    ("Taiwan", "TWN"),
    ("Tajiquistao", "TJK"),
    ("Tanzania", "TZA"),
    ("Timor-Leste", "TLS"),
    ("Togo", "TGO"),
    ("Tonga", "TON"),
    ("Trinidad e Tobago", "TTO"),
    ("Tunisia", "TUN"),
    ("Turcomenistao", "TKM"),
    ("Turquia", "TUR"),
    ("Tuvalu", "TUV"),
    ("Ucrania", "UKR"),
    ("Uganda", "UGA"),
    ("Uruguai", "URY"),
    ("Uzbequistao", "UZB"),
    ("Vanuatu", "VUT"),
    ("Vaticano", "VAT"),
    ("Venezuela", "VEN"),
    ("Vietna", "VNM"),
    ("Zambia", "ZMB"),
    ("Zimbabue", "ZWE"),
]


class Command(BaseCommand):
    help = 'Seed the database with all countries'

    def handle(self, *args, **options):
        self.stdout.write('Starting country seed...')

        created_count = 0
        existing_count = 0

        for name, acronym in COUNTRIES:
            _, created = Country.objects.get_or_create(
                acronym=acronym,
                defaults={'name': name},
            )

            if created:
                created_count += 1
                self.stdout.write(f'  [OK] Created: {name} ({acronym})')
            else:
                existing_count += 1

        self.stdout.write('')
        self.stdout.write('Country seed completed!')
        self.stdout.write(f'  Created: {created_count}')
        self.stdout.write(f'  Already existing: {existing_count}')
        self.stdout.write(f'  Total: {Country.objects.count()}')