# Generated by Django 6.0.5 on 2026-06-16 17:20

import django.db.models.deletion
import enterprises.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[enterprises.validators.validate_cnpj],
                    ),
                ),
                ("sap_code", models.CharField(blank=True, max_length=50, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enterprise",
                "verbose_name_plural": "Enterprises",
                "db_table": "db_enterprise",
            },
        ),
    ]
