# Generated by Django 6.0.5 on 2026-06-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "verbose_name": "Priority of Ticket",
                "verbose_name_plural": "Priorities of Ticket",
                "db_table": "db_ticket_priority",
            },
        ),
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("is_default", models.BooleanField(default=False)),
                ("is_final", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Status of Ticket",
                "verbose_name_plural": "Status of Tickets",
                "db_table": "db_ticket_status",
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "verbose_name": "Type of Ticket",
                "verbose_name_plural": "Type of Tickets",
                "db_table": "db_ticket_type",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=150)),
                ("subject", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("op_number", models.PositiveIntegerField(blank=True, null=True)),
                ("sector_id", models.UUIDField(blank=True, null=True)),
                (
                    "sector_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="machines.machine",
                    ),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True, related_name="mentioned_in", to="tickets.ticket"
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="tickets.ticketpriority",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="tickets.ticketstatus",
                    ),
                ),
                (
                    "type_of_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="tickets.tickettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "db_ticket",
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Attachment",
                "verbose_name_plural": "Ticket Attachments",
                "db_table": "db_ticket_attachment",
            },
        ),
        migrations.CreateModel(
            name="TicketLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("user_name", models.CharField(blank=True, default="", max_length=150)),
                ("action", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log of Ticket",
                "verbose_name_plural": "Logs of Ticket",
                "db_table": "db_ticket_log",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Recipient",
                "verbose_name_plural": "Ticket Recipients",
                "db_table": "db_ticket_recipient",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "user_id"), name="unique_ticket_recipient"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket View",
                "verbose_name_plural": "Ticket Views",
                "db_table": "db_ticket_view",
                "ordering": ["-viewed_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "user_id"), name="unique_ticket_view"
                    )
                ],
            },
        ),
    ]
