# Generated by Django 6.0.5 on 2026-08-31 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketWatcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("sector", "Setor"), ("department", "Departamento")],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "target_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Escolhido"),
                            ("department", "Veio do departamento"),
                            ("mention", "Veio de uma menção"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Watcher",
                "verbose_name_plural": "Ticket Watchers",
                "db_table": "db_ticket_watcher",
                "indexes": [
                    models.Index(
                        fields=["ticket", "kind"], name="db_ticket_w_ticket__5b0b43_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "kind", "target_id"),
                        name="unique_ticket_watcher",
                    )
                ],
            },
        ),
    ]
