# Generated by Django 6.0.5 on 2026-08-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticketwatcher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketwatcher",
            options={
                "ordering": ["kind", "created_at"],
                "verbose_name": "Ticket Watcher",
                "verbose_name_plural": "Ticket Watchers",
            },
        ),
    ]
