# Generated by Django 6.0.5 on 2026-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticketwatcher_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketwatcher",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Escolhido"),
                    ("department", "Veio do departamento"),
                    ("mention", "Veio de uma menção"),
                    ("requester", "Setor de quem abriu"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
