# Generated by Django 6.0.5 on 2026-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticketwatcher_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketstatus",
            name="is_in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
