# Generated by Django 6.0.5 on 2026-09-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ticketstatus_is_in_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketpriority",
            options={
                "ordering": ["-level", "name"],
                "verbose_name": "Priority of Ticket",
                "verbose_name_plural": "Priorities of Ticket",
            },
        ),
        migrations.AddField(
            model_name="ticketpriority",
            name="level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
