# Generated by Django 6.0.5 on 2026-09-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_ticketpriority_backfill_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketpriority",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
    ]
