# Generated by Django 6.0.5 on 2026-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_id", models.UUIDField()),
                ("actor_id", models.UUIDField()),
                ("actor_name", models.CharField(max_length=150)),
                ("message", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "db_notification",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["recipient_id", "is_read"],
                        name="db_notifica_recipie_65b7c8_idx",
                    )
                ],
            },
        ),
    ]
